version: '3.4'

services:
  client:
    image: client
    volumes:
      - ./client:/usr/src/app
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
      - 9229:9229
    networks:
      - mern-app
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
  server:
    image: server
    volumes:
      - ./server:/usr/src/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9230:9230
    networks:
      - mern-app
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
  mongo:
    image: mongo:3.6.20-xenial
    ports:
      - 27017:27017
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
      
networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
